"""player stats

Revision ID: 03b480c93aa2
Revises: 89e11ab309ae
Create Date: 2018-11-20 18:56:46.244411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b480c93aa2'
down_revision = '89e11ab309ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('matches_won', sa.Integer(), nullable=False),
    sa.Column('matches_lost', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('total_stars', sa.Integer(), nullable=False),
    sa.Column('total_high_scores', sa.Integer(), nullable=False),
    sa.Column('total_low_scores', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'matches_played', 'matches_won', 'matches_lost', 'games_played', 'games_won', 'total_stars', 'total_high_scores', 'total_low_scores')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_statistics')
    # ### end Alembic commands ###
