"""playerrole

Revision ID: 0a43b0bbf72a
Revises: 9dca0d703f35
Create Date: 2019-09-23 17:05:02.046067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a43b0bbf72a'
down_revision = '9dca0d703f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_player_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_role'))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
