"""player last active

Revision ID: 0d9fc16eed25
Revises: 63d3bfa284ee
Create Date: 2018-11-28 16:40:55.636522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9fc16eed25'
down_revision = '63d3bfa284ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_player_last_active'), ['last_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_last_active'))
        batch_op.drop_column('last_active')

    # ### end Alembic commands ###
