"""season calendar

Revision ID: 14883a5dd702
Revises: e0ab6f1a73be
Create Date: 2019-09-25 15:18:04.337300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14883a5dd702'
down_revision = 'e0ab6f1a73be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_link', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('calendar_link')

    # ### end Alembic commands ###
