"""add match stats

Revision ID: 17cd4325737b
Revises: 3bb263390265
Create Date: 2018-12-20 13:09:23.637088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cd4325737b'
down_revision = '3bb263390265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars_d5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stars_d7', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stars_s5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_d5', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_d7', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_s5', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_stats', schema=None) as batch_op:
        batch_op.drop_column('wins_s5')
        batch_op.drop_column('wins_d7')
        batch_op.drop_column('wins_d5')
        batch_op.drop_column('stars_s5')
        batch_op.drop_column('stars_d7')
        batch_op.drop_column('stars_d5')

    # ### end Alembic commands ###
