"""playermatchcheckin

Revision ID: 19e77171b897
Revises: 4aae58a70cc1
Create Date: 2019-08-28 16:37:50.917488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e77171b897'
down_revision = '4aae58a70cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_match_checkin',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name=op.f('fk_player_match_checkin_match_id_match')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_player_match_checkin_player_id_player')),
    sa.PrimaryKeyConstraint('player_id', 'match_id', name=op.f('pk_player_match_checkin'))
    )
    with op.batch_alter_table('player_match_checkin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_checkin_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_checkin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_checkin_status'))

    op.drop_table('player_match_checkin')
    # ### end Alembic commands ###
