"""match summary email

Revision ID: 1a1ff6713d02
Revises: 14883a5dd702
Create Date: 2019-10-01 13:32:29.925681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1ff6713d02'
down_revision = '14883a5dd702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_email_sent', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('summary_email_sent')

    # ### end Alembic commands ###
