"""season model

Revision ID: 1da835fbb866
Revises: 8689d43c428c
Create Date: 2018-11-27 16:58:53.743252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da835fbb866'
down_revision = '8689d43c428c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_name', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season'))
    )
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_season_season_name'), ['season_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_season_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_start_date'))
        batch_op.drop_index(batch_op.f('ix_season_season_name'))
        batch_op.drop_index(batch_op.f('ix_season_end_date'))

    op.drop_table('season')
    # ### end Alembic commands ###
