"""home_away

Revision ID: 201028c9962b
Revises: 10f061ebedb6
Create Date: 2018-11-24 11:51:49.599968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201028c9962b'
down_revision = '10f061ebedb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_away', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_match_home_away'), ['home_away'], unique=False)
        batch_op.drop_index('ix_match_home_game')
        batch_op.drop_column('home_game')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_game', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_match_home_game', ['home_game'], unique=False)
        batch_op.drop_index(batch_op.f('ix_match_home_away'))
        batch_op.drop_column('home_away')

    # ### end Alembic commands ###
