"""modify player

Revision ID: 24448892e1b1
Revises: f3e073d69292
Create Date: 2018-11-22 13:51:22.139654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24448892e1b1'
down_revision = 'f3e073d69292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_player_nickname'), ['nickname'], unique=True)
        batch_op.drop_index('ix_player_email')
        batch_op.create_index(batch_op.f('ix_player_email'), ['email'], unique=False)
        batch_op.drop_index('ix_player_name')
        batch_op.drop_column('name')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_player_name', ['name'], unique=1)
        batch_op.drop_index(batch_op.f('ix_player_email'))
        batch_op.create_index('ix_player_email', ['email'], unique=1)
        batch_op.drop_index(batch_op.f('ix_player_nickname'))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
