"""player last_match

Revision ID: 331031fda474
Revises: 0d9fc16eed25
Create Date: 2018-11-29 09:01:39.580752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331031fda474'
down_revision = '0d9fc16eed25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index('ix_player_last_active')
        batch_op.drop_column('last_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', sa.DATE(), nullable=True))
        batch_op.create_index('ix_player_last_active', ['last_active'], unique=False)

    # ### end Alembic commands ###
