"""matchstats

Revision ID: 3bb263390265
Revises: f9e240169778
Create Date: 2018-12-19 18:25:02.638741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb263390265'
down_revision = 'f9e240169778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name=op.f('fk_match_stats_match_id_match')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_stats'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_stats')
    # ### end Alembic commands ###
