"""match score

Revision ID: 40ac5e6a062c
Revises: 8a3c2ee3d641
Create Date: 2018-11-19 19:31:07.894025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ac5e6a062c'
down_revision = '8a3c2ee3d641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_match_opponent_score'), ['opponent_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_team_score'), ['team_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_win'), ['win'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_win'))
        batch_op.drop_index(batch_op.f('ix_match_team_score'))
        batch_op.drop_index(batch_op.f('ix_match_opponent_score'))
        batch_op.drop_column('win')
        batch_op.drop_column('team_score')
        batch_op.drop_column('opponent_score')

    # ### end Alembic commands ###
