"""remove stats

Revision ID: 40eb035ae7c7
Revises: c9642f782de5
Create Date: 2018-11-28 16:14:44.725239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40eb035ae7c7'
down_revision = 'c9642f782de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_season_stats')
    op.drop_table('player_season_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.Column('season_id', sa.INTEGER(), nullable=True),
    sa.Column('matches_played', sa.INTEGER(), nullable=False),
    sa.Column('matches_won', sa.INTEGER(), nullable=False),
    sa.Column('matches_lost', sa.INTEGER(), nullable=False),
    sa.Column('games_played', sa.INTEGER(), nullable=False),
    sa.Column('games_won', sa.INTEGER(), nullable=False),
    sa.Column('games_lost', sa.INTEGER(), nullable=False),
    sa.Column('total_stars', sa.INTEGER(), nullable=False),
    sa.Column('total_high_scores', sa.INTEGER(), nullable=False),
    sa.Column('total_low_scores', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name='fk_player_season_stats_player_id_player'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name='fk_player_season_stats_season_id_season'),
    sa.PrimaryKeyConstraint('id', 'matches_played', 'matches_won', 'matches_lost', 'games_played', 'games_won', 'games_lost', 'total_stars', 'total_high_scores', 'total_low_scores', name='pk_player_season_stats')
    )
    op.create_table('team_season_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('season_id', sa.INTEGER(), nullable=True),
    sa.Column('matches_played', sa.INTEGER(), nullable=False),
    sa.Column('matches_won', sa.INTEGER(), nullable=False),
    sa.Column('matches_lost', sa.INTEGER(), nullable=False),
    sa.Column('games_played', sa.INTEGER(), nullable=False),
    sa.Column('games_won', sa.INTEGER(), nullable=False),
    sa.Column('total_stars', sa.INTEGER(), nullable=False),
    sa.Column('total_high_scores', sa.INTEGER(), nullable=False),
    sa.Column('total_low_scores', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name='fk_team_season_stats_season_id_season'),
    sa.PrimaryKeyConstraint('id', 'matches_played', 'matches_won', 'matches_lost', 'games_played', 'games_won', 'total_stars', 'total_high_scores', 'total_low_scores', name='pk_team_season_stats')
    )
    # ### end Alembic commands ###
