"""non nullable remindersettings

Revision ID: 449887d27a3d
Revises: 7f223bd8da3c
Create Date: 2019-09-19 16:57:33.103753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449887d27a3d'
down_revision = '7f223bd8da3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_settings', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('days_in_advance',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_settings', schema=None) as batch_op:
        batch_op.alter_column('days_in_advance',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
