"""player season stats

Revision ID: 532d01f27de1
Revises: 1da835fbb866
Create Date: 2018-11-27 16:59:21.484812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532d01f27de1'
down_revision = '1da835fbb866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_season_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('matches_won', sa.Integer(), nullable=False),
    sa.Column('matches_lost', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('total_stars', sa.Integer(), nullable=False),
    sa.Column('total_high_scores', sa.Integer(), nullable=False),
    sa.Column('total_low_scores', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'matches_played', 'matches_won', 'matches_lost', 'games_played', 'games_won', 'total_stars', 'total_high_scores', 'total_low_scores', name=op.f('pk_player_season_statistics'))
    )
    op.drop_table('player_statistics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_statistics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('matches_played', sa.INTEGER(), nullable=False),
    sa.Column('matches_won', sa.INTEGER(), nullable=False),
    sa.Column('matches_lost', sa.INTEGER(), nullable=False),
    sa.Column('games_played', sa.INTEGER(), nullable=False),
    sa.Column('games_won', sa.INTEGER(), nullable=False),
    sa.Column('total_stars', sa.INTEGER(), nullable=False),
    sa.Column('total_high_scores', sa.INTEGER(), nullable=False),
    sa.Column('total_low_scores', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'matches_played', 'matches_won', 'matches_lost', 'games_played', 'games_won', 'total_stars', 'total_high_scores', 'total_low_scores')
    )
    op.drop_table('player_season_statistics')
    # ### end Alembic commands ###
