"""match reminderemailsent

Revision ID: 5758066be55b
Revises: 19e77171b897
Create Date: 2019-08-29 14:52:50.087106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5758066be55b'
down_revision = '19e77171b897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_email_sent', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('reminder_email_sent')

    # ### end Alembic commands ###
