"""teamsts update

Revision ID: 588aee487285
Revises: 6b8ece1717c0
Create Date: 2018-11-27 20:57:47.827345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588aee487285'
down_revision = '6b8ece1717c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_season_statistics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_season_statistics_team_id_team', type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_season_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_team_season_statistics_team_id_team', 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###
