"""player last_match fk

Revision ID: 59e712b1ab98
Revises: 331031fda474
Create Date: 2018-11-29 09:03:08.143126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e712b1ab98'
down_revision = '331031fda474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_match_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_player_last_match_id_match'), 'match', ['last_match_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_player_last_match_id_match'), type_='foreignkey')
        batch_op.drop_column('last_match_id')

    # ### end Alembic commands ###
