"""Game win

Revision ID: 6425cdc4c19a
Revises: f52d3f860af0
Create Date: 2018-11-19 13:53:34.094547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6425cdc4c19a'
down_revision = 'f52d3f860af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('win', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_win'), ['win'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_win'))
        batch_op.drop_column('win')

    # ### end Alembic commands ###
