"""player season stats update

Revision ID: 6b8ece1717c0
Revises: ce85b497ec3d
Create Date: 2018-11-27 17:05:20.714992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8ece1717c0'
down_revision = 'ce85b497ec3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_season_statistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_player_season_statistics_player_id_player'), 'player', ['player_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_season_statistics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_player_season_statistics_player_id_player'), type_='foreignkey')
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###
