"""high/low score

Revision ID: 89a6f42ad800
Revises: d39d0b41b11e
Create Date: 2018-12-03 10:07:58.950268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a6f42ad800'
down_revision = 'd39d0b41b11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('high_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name=op.f('fk_high_score_match_id_match')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_high_score_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_high_score'))
    )
    op.create_table('low_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name=op.f('fk_low_score_match_id_match')),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_low_score_player_id_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_low_score'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('low_score')
    op.drop_table('high_score')
    # ### end Alembic commands ###
