"""game_stars

Revision ID: 8a3c2ee3d641
Revises: 09b974ced5e2
Create Date: 2018-11-19 16:04:57.093856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3c2ee3d641'
down_revision = '09b974ced5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_player_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_last_name'), ['last_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_last_name'))
        batch_op.drop_index(batch_op.f('ix_player_first_name'))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
