"""match fields

Revision ID: 909dd999d166
Revises: 40ac5e6a062c
Create Date: 2018-11-20 15:42:20.359163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909dd999d166'
down_revision = '40ac5e6a062c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('match_summary', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('match_summary')
        batch_op.drop_column('location')
        batch_op.drop_column('food')

    # ### end Alembic commands ###
