"""add capt_report_sent_

Revision ID: 9dca0d703f35
Revises: 449887d27a3d
Create Date: 2019-09-22 21:42:54.587206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dca0d703f35'
down_revision = '449887d27a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captain_report_sent', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('captain_report_sent')

    # ### end Alembic commands ###
