"""match_poll

Revision ID: adf92ce97809
Revises: 5cb9b596c311
Create Date: 2019-10-06 10:18:52.868099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf92ce97809'
down_revision = '5cb9b596c311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], name=op.f('fk_poll_match_id_match')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poll'))
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name=op.f('fk_option_player_id_player')),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], name=op.f('fk_option_poll_id_poll')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option'))
    )
    op.create_table('voters',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], name=op.f('fk_voters_poll_id_poll')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_voters_user_id_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voters')
    op.drop_table('option')
    op.drop_table('poll')
    # ### end Alembic commands ###
