"""pss id3

Revision ID: c9642f782de5
Revises: 7bad087356cd
Create Date: 2018-11-28 16:12:32.847967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9642f782de5'
down_revision = '7bad087356cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.alter_column('games_lost',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_played',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_won',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('matches_lost',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('matches_played',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('matches_won',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_high_scores',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_low_scores',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_stars',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('team_season_stats', schema=None) as batch_op:
        batch_op.alter_column('games_played',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_won',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('matches_lost',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('matches_played',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('matches_won',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_high_scores',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_low_scores',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_stars',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_season_stats', schema=None) as batch_op:
        batch_op.alter_column('total_stars',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_low_scores',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_high_scores',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('matches_won',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('matches_played',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('matches_lost',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_won',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_played',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.alter_column('total_stars',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_low_scores',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_high_scores',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('matches_won',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('matches_played',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('matches_lost',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_won',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_played',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_lost',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
