"""player first_match fk

Revision ID: d39d0b41b11e
Revises: 59e712b1ab98
Create Date: 2018-11-29 09:39:17.552127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39d0b41b11e'
down_revision = '59e712b1ab98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_match_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_player_first_match_id_match'), 'match', ['first_match_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_player_first_match_id_match'), type_='foreignkey')
        batch_op.drop_column('first_match_id')

    # ### end Alembic commands ###
