"""match date type

Revision ID: e0ab6f1a73be
Revises: ecc976d54660
Create Date: 2019-09-24 14:12:29.147650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ab6f1a73be'
down_revision = 'ecc976d54660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'date', existing_type=sa.DateTime(), type_=sa.Date())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'date', existing_type=sa.Date(), type_=sa.DateTime())

    # ### end Alembic commands ###
