"""team model

Revision ID: e3ea144378fc
Revises: 909dd999d166
Create Date: 2018-11-20 18:36:01.284571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ea144378fc'
down_revision = '909dd999d166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('home_location', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_home_location'), ['home_location'], unique=True)
        batch_op.create_index(batch_op.f('ix_team_address'), ['address'], unique=True)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index('ix_match_opponent')
        batch_op.drop_column('opponent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_match_opponent', ['opponent'], unique=False)

    # ### end Alembic commands ###
