"""team model

Revision ID: e3ea144378fc
Revises: 909dd999d166
Create Date: 2018-11-20 18:36:01.284571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ea144378fc'
down_revision = '909dd999d166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index('ix_match_opponent')
        batch_op.drop_column('opponent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_match_opponent', ['opponent'], unique=False)

    # ### end Alembic commands ###
