"""rematch_player_role_is_active_update

Revision ID: ecc976d54660
Revises: 0a43b0bbf72a
Create Date: 2019-09-24 09:43:04.268381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc976d54660'
down_revision = '0a43b0bbf72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index('ix_player_is_active')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_role')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=32), nullable=True))
        batch_op.create_index('ix_user_role', ['role'], unique=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.create_index('ix_player_is_active', ['is_active'], unique=False)

    # ### end Alembic commands ###
