"""settings reminders_ifnr

Revision ID: ed8723fd5c0c
Revises: e4c82ae4d694
Create Date: 2019-11-30 13:05:53.562364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8723fd5c0c'
down_revision = 'e4c82ae4d694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_reminders_if_nr', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_settings_email_reminders_if_nr'), ['email_reminders_if_nr'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_email_reminders_if_nr'))
        batch_op.drop_column('email_reminders_if_nr')

    # ### end Alembic commands ###
