"""player active

Revision ID: f4f4ca2e0950
Revises: fecb4ca8519b
Create Date: 2019-06-05 09:10:38.746199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f4ca2e0950'
down_revision = 'fecb4ca8519b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_player_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_is_active'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
