"""match ovetime

Revision ID: f9e240169778
Revises: 12c337e881d9
Create Date: 2018-12-17 15:17:22.470228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e240169778'
down_revision = '12c337e881d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overtime', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_match_overtime'), ['overtime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_overtime'))
        batch_op.drop_column('overtime')

    # ### end Alembic commands ###
